groups:
    - bash
    - developer
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: Lunar
    homebrewalt:
        apps:
            - git-extras
            - tower
            - things
            - alfred
